### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by alexapostolu** [firefish111/dusk#1]
what about the name `ngt`? idk, I do like the name dusk though.

okay so is the plan for me to add something to my language like `include math`, and that will run this shell script: `dusk add math`?

**Comment by firefish111** [comment]
Well as long as a package called "math" exists on the cdn, then it'll work. otherwise it'll panic (the golang equivalent of throwing an exception)

**Comment by firefish111** [comment]
Also, as we said, this may not be seperate. If you want to build the sources locally or on repl.it to EXPERIMENT then... that's absolutely fine, I infact encourage it

**Comment by firefish111** [comment]
@DynamicSquid There could be something like `night -i example` instead of the long winded `dusk add example`. But python has it's package manager seperate, called `pip`. Node has `npm` seperate as well. Go with the majority, or something else? Your choice.

**Comment by firefish111** [comment]
So, should we do like python and pip, node and npm, or squash them into one binary? both are possible at the moment @DynamicSquid

**Comment by alexapostolu** [comment]
i confused

**Comment by firefish111** [comment]
do you want night and dusk seperate like python and node did it, or should they be squished together into one thing? that's all I ask @DynamicSquid 
(Also now you can update packages!)

**Comment by alexapostolu** [comment]
which one's easier for the user and me to understand?

**Comment by firefish111** [comment]
um well keeping them seperate is easier because `night --install example` isn't very enticing

**Comment by alexapostolu** [comment]
okay

**Comment by firefish111** [comment]
Should I keep the two (night and dusk) in the same repo or not?

**Comment by alexapostolu** [comment]
oh cool you released it! almost done v3.0 if the bugs don't drown me, I can get it out tmr in the afternoon
