### ISSUE TITLE
Colours aren't working

### ISSUE THREAD

**Issue by alexapostolu** [firefish111/dusk#7]
You have to do `\033` instead of `\x1b`, well, for windows at least

**Comment by firefish111** [comment]
@DynamicSquid Will address, it works on mingw (my testing platform). NOW PLEASE STOP CREATING NEW BLASTED ISSUES

**Comment by alexapostolu** [comment]
Sorry

**Comment by iop3** [comment]
> NOW PLEASE STOP CREATING NEW BLASTED ISSUES

:O

**Comment by firefish111** [comment]
# AND STOP GIVING ME NOTIFICATIONS
