### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by programmeruser2** [firefish111/dusk#9]
I'm not trying to insult you, but this honestly seems like a glorified file downloader that stores the versions in a JSON file and uses that to update packages.
Here are some suggestions:
* Dependency resolution
* Project metadata files (like `package.json` in Node.js)
* Ability to publish new packages

**Comment by alexapostolu** [comment]
> Ability to publish new packages

Not yet. We need a way better system, which is a long ways away.

But other than that, those seem like really good ideas. What do you think @firefish111?

**Comment by firefish111** [comment]
The first two were planned, but that was when dusk was a priority (back in
September 2020). @programmeruser2 @DynamicSquid

**Comment by zghwi** [comment]
@firefish111 @DynamicSquid 

im good at golang
and i'll think of contributing to dusk, to create the ability to publish packages
i made a package manager for my own [programming language](https://github.com/zplusfour/aardvark) (~~please star~~)
and i've added the ability to publish packages
but the problem that it's written in js
but i can try with golang ;)

[aardvark's package manager](https://github.com/zplusfour/apm)

**Comment by firefish111** [comment]
@xplusfour brrrrrr let me do it I just need to think about it... As I said,
they were planned back September, which is 6 months ago now? You can help,
I'll invite you to the repl reeeee

**Comment by zghwi** [comment]
reeeeeeeeeeeeeeee
> its zplusfour btw

**Comment by firefish111** [comment]
l'yes @zplusfour

**Comment by firefish111** [comment]
# brrrrrrrrrrrrrrrrrrrrrrrr
